backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "assets/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{ slug }}"
        create: false
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/homepage.njk"}
